services:
  - type: web
    name: blogapp-backend
    env: java
    buildCommand: chmod +x ./mvnw && ./mvnw clean package -DskipTests
    startCommand: java -jar target/blogapp-0.0.1-SNAPSHOT.jar
    plan: free
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: SPRING_PROFILES_ACTIVE
        value: production
      # Add DATABASE_URL and CORS_ORIGINS manually in Render dashboard
